### ISSUE TITLE
[Impl] Implement on-chain Metadata contractURI 

### ISSUE THREAD

**Issue by tekkac** [Carbonable/metadata-cairo0#2]
**Description**
---
Implement on-chain dynamic metadata for `contactURI` 

Use and convert the existing Metadata when possible;

**Acceptance Criteria**
--- 

- [x] Implementation of the method 
- [x] Unit and Integration Tests

**Comment by cloudvenger** [comment]
Create a new Issue for the `slotURI` and remove from this Issue
