### ISSUE TITLE
[Impl] Implement Metadata for each Mainnet Carbonable project

### ISSUE THREAD

**Issue by tekkac** [Carbonable/metadata-cairo0#3]
**Description**
---
Add a `.cairo` file for each Carbonable project and implement the methods:
 - `contractURI`
 - `slotURI`
 - `tokenURI`

**Resources**
--- 

  - [Current Metadata Airtable](https://airtable.com/appj3XhJLQdL25lLx/tblmleZkgfSWTJL8a/viw4PnUzMyAwneUtG?blocks=hide)
  - [Old Metadata Server](https://dev-carbonable-metadata.fly.dev/collection/1)
 
**Acceptance Criteria**
--- 

- [ ] metadata parity with production metadata
- [ ] every project metadata is implemented
- [ ] unit and integration tests pass

**Comment by cloudvenger** [comment]
Prerequire : 
Add the list of projects we want to integrate.
